import matplotlib.pyplot as plt
import numpy as np

def plot_analysis(original, cleaned, fs, save=True, output_file='noise_reduction_analysis.png'):
    """Generate comparison plots for original and cleaned signals."""
    try:
        t = np.arange(len(original)) / fs
        plt.figure(figsize=(15, 12))
        plt.subplot(3, 2, 1)
        plt.plot(t[:8000], original[:8000], 'b-', alpha=0.7, label='Orijinal')
        plt.title('Orijinal Sinyal (Zaman Domain)')
        plt.xlabel('Zaman (s)')
        plt.ylabel('Amplitüd')
        plt.grid(True, alpha=0.3)
        plt.legend()
        plt.subplot(3, 2, 2)
        plt.plot(t[:8000], cleaned[:8000], 'r-', alpha=0.7, label='Temizlenmiş')
        plt.title('Temizlenmiş Sinyal (Zaman Domain)')
        plt.xlabel('Zaman (s)')
        plt.ylabel('Amplitüd')
        plt.grid(True, alpha=0.3)
        plt.legend()
        n_fft = min(4096, len(original))
        fft_orig = np.fft.fft(original[:n_fft])
        fft_clean = np.fft.fft(cleaned[:n_fft])
        freqs = np.arange(n_fft // 2) * fs / n_fft
        plt.subplot(3, 2, 3)
        plt.semilogy(freqs, np.abs(fft_orig[:n_fft//2]), 'b-', alpha=0.7)
        plt.title('Orijinal Spektrum')
        plt.xlabel('Frekans (Hz)')
        plt.ylabel('Magnitude')
        plt.grid(True, alpha=0.3)
        plt.xlim(0, fs//2)
        plt.subplot(3, 2, 4)
        plt.semilogy(freqs, np.abs(fft_clean[:n_fft//2]), 'r-', alpha=0.7)
        plt.title('Temizlenmiş Spektrum')
        plt.xlabel('Frekans (Hz)')
        plt.ylabel('Magnitude')
        plt.grid(True, alpha=0.3)
        plt.xlim(0, fs//2)
        plt.subplot(3, 2, 5)
        plt.semilogy(freqs, np.abs(fft_orig[:n_fft//2]), 'b-', alpha=0.7, label='Orijinal')
        plt.semilogy(freqs, np.abs(fft_clean[:n_fft//2]), 'r-', alpha=0.7, label='Temizlenmiş')
        plt.title('Spektrum Karşılaştırması')
        plt.xlabel('Frekans (Hz)')
        plt.ylabel('Magnitude')
        plt.legend()
        plt.grid(True, alpha=0.3)
        plt.xlim(0, fs//2)
        plt.subplot(3, 2, 6)
        noise_reduction = 20 * np.log10(np.abs(fft_orig[:n_fft//2]) / (np.abs(fft_clean[:n_fft//2]) + 1e-10))
        plt.plot(freqs, noise_reduction, 'g-', alpha=0.7)
        plt.title('Gürültü Azalma (dB)')
        plt.xlabel('Frekans (Hz)')
        plt.ylabel('Azalma (dB)')
        plt.grid(True, alpha=0.3)
        plt.xlim(0, fs//2)
        plt.tight_layout()
        if save:
            plt.savefig(output_file, dpi=150, bbox_inches='tight')
            print(f"Plot saved: {output_file}")
        plt.show()
    except Exception as e:
        print(f"Plotting error: {e}")
